### ISSUE TITLE
Pip error 

### ISSUE THREAD

**Issue by RRetro7** [termux/termux.com#5]
I received this error, solve this

`ERROR: Installing pip is forbidden, this will break the python-pip package (termux).
Requirement already satisfied: requests in /data/data/com.termux/files/usr/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from requests) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from requests) (2023.7.22)![Screenshot_2023-09-10-15-24-16-972_com.termux.jpg](https://github.com/termux/termux.com/assets/144549508/7c778ffc-f738-472c-a8a9-942c2dec4471)

![Screenshot_2023-09-10-15-24-16-972_com.termux.jpg](https://github.com/termux/termux.com/assets/144549508/06d1ab4e-6764-4d02-8afc-34d72f1ae4de)

`

**Comment by Grimler91** [comment]
This is per design. Upgrade python-pip through apt.
